library(plyr)
#merging the two files: agency & programs
	#first create df1 program (i.e. long format) data frame
df1<-read.csv(file="nmrcsurvey/long.csv",header=TRUE)
	#second create df2 agency (i.e. wide) data frame  
df2<-read.csv(file="nmrcsurvey/wide.csv",header=TRUE)
	#finally, merge the data 
dfm<-merge(x=df2[,1:237],y=df1,by="Response.ID",all=TRUE)
  #Rename all merged variables to be consistent with codebook
dfmr<-rename(test,
             c(
               #NOTE: All columns are directly pulled from gizmo. Spaces are replaced with periods (i.e. "."), all other punctuation removed.
               #Comments are placed to identify survey question change for multi-response questions
               "Response.ID"="ID", #ID
               "Time.Started"="TS",
               "Date.Submitted"="DS",
               "Status"="STAT",
               "Contact.ID"="CONTID",
               "Legacy.Comments"="LEGCOM",                                                                                                                                                                     
               "Comments"="COM",                                                                                                                                                                            
               "Language"="LANG",                                                                                                                                                                           
               "Referer"="REF",                                                                                                                                                                             
               "Extended.Referer"="EXREF",                                                                                                                                                                    
               "SessionID"="SESID",                                                                                                                                                                           
               "User.Agent"="USAG",
               "Extended.User.Agent"="EXUSAG",
               "Tags"="TAGS",
               "IP.Address"="IP",
               "Longitude"="LON",
               "Latitude"="LAT",
               "Country"="CONTR",
               "City"="CIT",
               "State.Region"="ST",
               "Postal"="PSTL",
               "Name.of.survey.respondent."="NAME",
               "What.is.your.email.address."="EMAIL",
               "What.position.do.you.hold.in.the.organization.agency."="ORGPOS",
               "Other...Write.In.What.position.do.you.hold.in.the.organization.agency."="ORGPOSOTH",
               "What.is.the.name.of.your.organization.agency."="ORGNAME",
               "What.city.is.your.organization.agency.based.in."="ORGCIT",
               "Which.state.your.organization.agency.is.based.in."="ORGST",
               "What.ZIP.code.is.your.organization.agency.based.in."="ORGZIP",
               #"NS1" is the first question in the survey."Our agency is a..."
               "Other...Write.In.NS1"="NS1O",
               #"NS2" How many individual mentoring programs does your agency operate
               #"NS10" How many of these mentoring programs would you like to report on in this survey?
               "Academic.support.programs.NS3"="NS3Q1",
               "After.school.daycare.programs.NS3"="NS3Q2",
               "Case.management.NS3"="NS3Q3",
               "College.and.career.readiness.NS3"="NS3Q4",
               "Drop.in.center.homeless.runaway.services.NS3"="NS3Q5",
               "Education..Primary.or.Secondary.school..NS3"="NS3Q6",
               "Empowerment.leadership.development.NS3"="NS3Q7",
               "Foster.care.or.services.for.foster.youth.NS3"="NS3Q8",
               "Independent.living.transition.aged.youth.services.NS3"="NS3Q9",
               "Medical.healthcare.services.NS3"="NS3Q10",
               "Mental.health.prevention.and.wellness.NS3"="NS3Q11",
               "Outpatient.psychiatric.treatment.NS3"="NS3Q12",
               "Positive.youth.development.NS3"="NS3Q13",
               "Pregnancy.prevention.NS3"="NS3Q14",
               "Psychological.counseling.NS3"="NS3Q15",
               "Residential.or.inpatient.psychiatric.treatment.NS3"="NS3Q16",
               "Service.learning.volunteerism.NS3"="NS3Q17",
               "Services.for.juvenile.justice.involved.youth.NS3"="NS3Q18",
               "Services.for.pregnant.and.parenting.teens.NS3"="NS3Q19",
               "Services.for.youth.with.disabilities.NS3"="NS3Q20",
               "Substance.use.disorder.prevention.or.treatment.NS3"="NS3Q21",
               "Violence.prevention.NS3"="NS3Q22",
               "Workforce.development.NS3"="NS3Q23",
               "Other...Write.In.NS3"="NS3QO",
               "Other...Write.In.NS3.1"="NS3QO1",
               #NS4 is the most successful recruitment strategies
               "Media.Public.relations.NS4"="NS4Q1",
               "National.Mentoring.Month.events.and.promotions.NS4"="NS4Q2",
               "Online.outreach..Facebook..program.website..etc...NS4"="NS4Q3",
               "Community.events.and.in.person.presentations.by.staff.NS4"="NS4Q4",
               "Referrals.from.community.partners.NS4"="NS4Q5",
               "Referrals.from.the.Mentoring.Connector.database.NS4"="NS4Q6",
               "Referrals.from.our.local..em.Mentoring.Partnership..em..NS4"="NS4Q7",
               "Volunteer.Centers.and.other.volunteer.organizations.NS4"="NS4Q8",
               "Word.of.mouth.from.current.or.former.mentors.NS4"="NS4Q9",
               "Other...Write.In.NS4"="NS4Q10",
               "Other...Write.In.NS4.1"="NS4Q11",
               #"NS5" asks familiarity with EEPM vs. 4
               #NS6 asks ab training/technical assistance provider 
               "MENTOR..The.National.Mentoring.Partnership.NS6"="NS6Q1",
               "State.or.Local.Mentoring.Partnership.NS6"="NS6Q2",
               "National.Mentoring.Resource.Center.NS6"="NS6Q3",
               "United.Way.or.other.funding.agency.NS6"="NS6Q4",
               "For.profit.consulting.firm.NS6"="NS6Q7",
               "Nonprofit.consulting.firm.NS6"="NS6Q",
               "Other...Write.In.NS6"="NS6QO",
               "Other...Write.In.NS6.1"="NS6QO1",
               #NS7 asks ab main challenges or areas of need
                "Blending.mentoring.with.other.services.NS7"="NS7Q1",
               "Cultural.perspectives.in.service.design.and.delivery.NS7"="NS7Q2",
               "Developing.meaningful.activities.for.mentors.and.youth.NS7"="NS7Q3",
               "Fundraising.grantwriting.NS7"="NS7Q4",
               "General.program.design.theory.of.change.NS7"="NS7Q5",
               "Integrating.youth.development.principles.NS7"="NS7Q6",
               "Making.strong.mentor.mentee.matches.NS7"="NS7Q7",
               "Mentor.recruitment.NS7"="NS7Q8",
               "Mentor.training..including.curriculum.development..NS7"="NS7Q9",
               "Offering.mentoring.in.rural.settings.NS7"="NS7Q10",
               "Parent.family.engagement.NS7"="NS7Q11",
               "Partnership.development.NS7"="NS7Q12",
               "Professional.development.of.staff.NS7"="NS7Q13",
               "Program.evaluation.data.collection.NS7"="NS7Q14",
               "Program.sustainability.growth.NS7"="NS7Q15",
               "Supporting.mentor.mentee.matches.NS7"="NS7Q16",
               "Other...Write.In.NS7"="NS7Q1O",
               "Other...Write.In.NS7.1"="NS7QO1",
               #NS8 asks ab evaluation questions
               "Qualitative.evaluation..examines.participant.experiences.through.interviews..end.of.year.satisfaction.surveys..case.notes..focus.groups..or.other.data.sources..NS8"="NS8Q1",                 
               "Implementation.evaluation..examines.how.well.or.efficiently.services.were.delivered.to.participants..such.as.tracking.mentor.mentee.meetings..participation.in.trainings..etc....NS8"="NS8Q2",
               "Outcome.evaluation..examines.changes.in.participants.served.using.pre.post.data.collection..NS8"="NS8Q3",                                                                                     
               "Experimental.or.quasi.experimental..evaluation..compares.mentored.youth.to.a.comparison.or.â.œcontrolâ...group.of.non.mentored.youth..NS8"="NS8Q4",                                           
               "Return.on.investment.study..examines.long.term.impacts.from.an.economic.perspective..often.in.relation.to.program.costs..NS8"="NS8Q5",                                                        
               "We.haven.t.engaged.in.any.evaluation.activities.NS8"="NS8Q6",                                                                                                                                 
               "Other...Write.In.NS8"="NS8QO",                                                                                                                                                                
               "Other...Write.In.NS8.1"="NS8QO1",
               #NS9 asks Who plays a role in planning and implementing your agency’s mentoring-related evaluation efforts?
               "Executive.Director.Program.Coordinator.NS9"="NS9Q1",
               "Staff.evaluation.specialist..internal.staff..NS9"="NS9Q2",
               "Professional.external.evaluator.NS9"="NS9Q3",
               "Funding.agency.or.philanthropy.NS9"="NS9Q4",
               "Our.local.Mentoring.Partnership.NS9"="NS9Q5",
               "School.or.district.staff.NS9"="NS9Q6",
               "We.have.not.done.any.evaluation.work.NS9"="NS9Q7",
               "Other...Write.In.NS9"="NS9QO",
               "Other...Write.In.NS9.1"="NS9QO1",
               #Ohio question re: Please select the elements you currently use or promote.
               "Regular.referral.of.mentors.to.Mentoring.Center.training.OHA1"="OHA1Q1",
               "Referral.of.mentors.to.the.Mentoring.Centerâ..s..a.href..http...www.metoringcenterco.org..target.._blank..website..a..OHA1"="OHA1Q2",
               "Participation.in.Mentoring.Month.January.Celebrations.OHA1"="OHA1Q3",                                                                                                                          
               "Nomination.of.Outstanding.Mentor.and.or.Mentee.awards.OHA1"="OHA1Q4",                                                                                                                          
               "Participation.in.January.FunDay.at.OSU..for.partner.agencies.only.in.central.Ohio..OHA1"="OHA1Q5",                                                                                             
               "Promotion.of.activities.through.Mentoring.Center.email.alerts.OHA1"="OHA1Q6",                                                                                                                  
               "E.newsletter.OHA1"="OHA1Q7",                                                                                                                                                                   
               "Scheduling.of.on.site.mentor.mentee.training.of.life.skill..goal.setting..leadership..etc...OHA1"="OHA1Q8",                                                                                    
               "Sending.mentors.to.the.Mentoring.Center.for.background.checks.OHA1"="OHA1Q9",                                                                                                                  
               "Referral.of.staff.for.background.checks.OHA1"="OHA1Q10",                                                                                                                                        
               "Inclusion.of.the.Mentoring.Center.in.your.grants.or.other.supports.OHA1"="OHA1Q11",                                                                                                             
               "Attendance.at.a.Design.and.Build.session...Element.of.Effective.Practice.for.Mentoring..prior.to.becoming.a.partner.agency.OHA1"="OHA1Q12",    
               #OHA2 asks For your mentors who attended training provided by the Mentoring Center, check all areas that apply.
               "Mentors..expectations.are..now..better.aligned.with.what.they.are.likely.to.encounter.OHA2"="OHA2Q1",
               "Mentors.understand.appropriate.roles.for.themselves.OHA2"="OHA2Q2",
               "Mentors.see.that.their.goal.is.to.address.the.whole.child..including.coaching.and.life.skills..e.g..decision.making..OHA2"="OHA2Q3",
               "Mentors.have.ideas.for.overcoming.obstacles.in.achieving.a.relationship.with.their.mentee.OHA2"="OHA2Q4",
               "Mentors.understand.the.importance.of.having.fun.as.part.of.establishing.a.quality.relationship.with.their.mentee.OHA2"="OHA2Q5",
               "Mentors.have.good.understanding.of.when.an.issue.needs.to.be.reported.to.their.agency.program.coordinator.OHA2"="OHA2Q6",                                                                      
               "Other...Write.In.OHA2"="OHA2QO",                                                                                                                                                               
               "Other...Write.In.OHA2.1"="OHA2QO1",
               #Virginia
               "Mentor.training.VAA1"="VAA1Q1",
               "Program.staff.training.VAA1"="VAA1Q2",
               "Consultation.on.new.program.development.VAA1"="VAA1Q3",
               "Consultation.on.existing.program.capacity.building.VAA1"="VAA1Q4",
               "Technical.assistance.through.the.NMRC.VAA1"="VAA1Q5",
               "AmeriCorps.VISTA.VAA1"="VAA1Q6",
               "Quality.Based.Membership.VAA1"="VAA1Q7",
               "Affiliate.Membership.VAA1"="VAA1Q8",
               "Newsletters.VAA1"="VAA1Q9",
               "Website.VAA1"="VAA1Q10",
               "Annual.Event.VAA1"="VAA1Q11",
               "Referrals.VAA1"="VAA1Q12",
               #VA Question #2
               "Mentor.training.VAA2"="VAA2Q1",
               "Program.staff.training.VAA2"="VAA2Q2",
               "Consultation.on.new.program.development.VAA2"="VAA2Q3",
               "Consultation.on.existing.program.development.VAA2"="VAA2Q4",
               "Technical.assistance.through.the.NMRC.VAA2"="VAA2Q5",
               "AmeriCorps.VISTA.VAA2"="VAA2Q6",
               "Quality.Based.Membership.VAA2"="VAA2Q7",
               "Affiliate.Membership.VAA2"="VAA2Q8",
               "Newsletters.VAA2"="VAA2Q9",
               "Website.VAA2"="VAA2Q10",
               "Annual.Event.VAA2"="VAA2Q11",
               "Referrals.VAA2"="VAA2Q12",
               "Building.blocks.for.mentoring.programs..building.a.foundation.in.Elements.of.Effective.Practice..VAA3"="VAA3Q1",
               "Match.support.mentor.retention.VAA3"="VAA3Q2", 
               "Screening.mentors.VAA3"="VAA3Q3",
               "Volunteer.and.mentor.recruitment.VAA3"="VAA3Q4", 
               "Program.evaluation.VAA3"="VAA3Q5",
               "Other...Write.In.VAA3"="VAA3QO",
               "Other...Write.In.VAA3.1"="VAA3QO1",
               #Virginia 4 asks VMP also offers a variety of ongoing mentor trainings. Please indicate which topics would be most beneficial for your agency's mentors. 
               "Becoming.a.more.culturally.competent.mentor.VAA4"="VAA4Q1",
               "Understanding.youth.culture.VAA4"="VAA4Q2",
               "Walking.with.mentees.on.the.path.to.college.VAA4"="VAA4Q3",
               "Child.development..generational.difference.and.communication.VAA4"="VAA4Q4",
               "Academic.mentoring.VAA4"="VAA4Q5",
               "Other...Write.In.VAA4"="VAA4QO",
               "Other...Write.In.VAA4.1"="VAA4QO1",
               #Is your mentoring program currently registered at on our Mentoring Partnership of Minnesota
               #"MNA1"                                                                                                                                                                                
               "Name.MNA2"="MNA2NAME",                                                                                                                                                                           
               "Email.MNA2"="MNA2EMAIL",
               "Accessed.in.2015.or.currently.access.Quality.Mentoring.Assessment.Path..QMAP..MNA3"="MNA3Q1",
               "Would.like.to.access.in.the.future.Quality.Mentoring.Assessment.Path..QMAP..MNA3"="MNA3Q2",
               "Accessed.in.2015.or.currently.access.Training.for.staff.MNA3"="MNA3Q3",
               "Would.like.to.access.in.the.future.Training.for.staff.MNA3"="MNA3Q4",
               "Accessed.in.2015.or.currently.access.Training.for.mentors.MNA3"="MNA3Q5",
               "Would.like.to.access.in.the.future.Training.for.mentors.MNA3"="MNA3Q6",
               "Accessed.in.2015.or.currently.access.Training.for.mentees.MNA3"="MNA3Q7",
               "Would.like.to.access.in.the.future.Training.for.mentees.MNA3"="MNA3Q8",
               "Accessed.in.2015.or.currently.access.Training.webinars.MNA3"="MNA3Q9",
               "Would.like.to.access.in.the.future.Training.webinars.MNA3"="MNA3Q10",
               "Accessed.in.2015.or.currently.access.Minnesota.Mentoring.Conference.MNA3"="MNA3Q11", 
               "Would.like.to.access.in.the.future.Minnesota.Mentoring.Conference.MNA3"="MNA3Q12",
               "Accessed.in.2015.or.currently.access.Program.consultation.or.technical.assistance.MNA3"="MNA3Q13",
               "Would.like.to.access.in.the.future.Program.consultation.or.technical.assistance.MNA3"="MNA3Q14",
               "Accessed.in.2015.or.currently.access.E.Newsletters.MNA3"="MNA3Q15",
               "Would.like.to.access.in.the.future.E.Newsletters.MNA3"="MNA3Q16",
               "Accessed.in.2015.or.currently.access.Resources..online.and.printed..MNA3"="MNA3Q17",
               "Would.like.to.access.in.the.future.Resources..online.and.printed..MNA3"="MNA3Q18",
               "Accessed.in.2015.or.currently.access.Website.listing.for.mentoring.program.MNA3"="MNA3Q19",
               "Would.like.to.access.in.the.future.Website.listing.for.mentoring.program.MNA3"="MNA3Q20",
               "Accessed.in.2015.or.currently.access.Tools.to.support.recruitment.and.public.awareness.campaigns.MNA3"="MNA3Q21",
               "Would.like.to.access.in.the.future.Tools.to.support.recruitment.and.public.awareness.campaigns.MNA3"="MNA3Q22",
               "Accessed.in.2015.or.currently.access.Grant.writing.assistance...Letters.of.support.for.funding.proposals.MNA3"="MNA3Q23",
               "Would.like.to.access.in.the.future.Grant.writing.assistance...Letters.of.support.for.funding.proposals.MNA3"="MNA3Q24",
               "Accessed.in.2015.or.currently.access.Referrals.to.funding.opportunities.MNA3"="MNA3Q25",
               "Would.like.to.access.in.the.future.Referrals.to.funding.opportunities.MNA3"="MNA3Q26",
               "Accessed.in.2015.or.currently.access.Alerts.about.upcoming.legislation.or.public.policy.activities.MNA3"="MNA3Q27",
               "Would.like.to.access.in.the.future.Alerts.about.upcoming.legislation.or.public.policy.activities.MNA3"="MNA3Q28",
               "Accessed.in.2015.or.currently.access.Opportunities.to.network.with.other.mentoring.organizations.MNA3"="MNA3Q29",
               "Would.like.to.access.in.the.future.Opportunities.to.network.with.other.mentoring.organizations.MNA3"="MNA3Q30",
               #"MNA4" Of the Mentoring Partnership of Minnesota resources you have accessed in 2015, or are currently accessing, which have been the most valuable or had the most impact for your organization, and why?                                                                                                                                                                                
               "None..we.did.not.engage.advocacy.or.public.policy.activities.in.2015.MNA6"="MNA6Q1",
               "Tracking.local..state.or.federal.policies.MNA6"="MNA6Q2",
               "Attending.public.policy.forums.or.information.meetings.MNA6"="MNA6Q3",
               "Building.relationships.with.local.and.or.state.policy.makers.MNA6"="MNA6Q4",
               "Responding.to.action.alerts.from.advocacy.groups.MNA6"="MNA6Q5",
               "Lobbying.for.legislation.or.policy.initiatives.at.the.local..state.or.federal.level.MNA6"="MNA6Q6",
               "Proposing.state.or.federal.legislation.MNA6"="MNA6Q7",
               "Other...Write.In.MNA6"="MNA6QO",
               "Other...Write.In.MNA6.1"="MNA6QO1",
               #"MNA5" Do you have ideas for other types of assistance that Mentoring Partnership of Minnesota could provide? How would this benefit your program/organization?                                                                                                                                                                                
               #"TXA1"  Have you heard of the Texas Mentoring Partnership, a new effort to advocate for and provide services to youth mentoring programs across Texas?                                                                                                                                                                              
               "Program.start.up.assistance.GAA1"="GAA1Q1",
               "Program.consultation...technical.assistance.GAA1"="GAA1Q2",
               "Training.GAA1"="GAA1Q3",
               "Grants...financial.awards.GAA1"="GAA1Q4",
               "Sharing.funding.opportunities.GAA1"="GAA1Q5",
               "Cultural.competency.and.inclusion.resources.GAA1"="GAA1Q6",
               "Match.activities.GAA1"="GAA1Q7",
               "Government.advocacy.GAA1"="GAA1Q8",
               "Public.awareness...mentor.recruitment.campaigns.GAA1"="GAA1Q9",
               "Partnership.development..e.g...businesses..schools..legislators..GAA1"="GAA1Q10",
               "Research.on.youth.mentoring.GAA1"="GAA1Q11",
               "Data.from.a.scan...landscape.analysis.of.mentoring.organizations.in.Georgia.GAA1"="GAA1Q12",
               "Networking.GAA1"="GAA1Q13",
               "Other...Write.In..Required..GAA1"="GAA1QO",
               "Other...Write.In..Required..GAA1.1"="GAA1QO1",
               #GAA2 asks Does your organization provide/require ongoing professional development that includes content on cultural and linguistic competency?
               "For.the.Board.GAA2"="GAA2Q1",
               "For.paid.staff.GAA2"="GAA2Q2",
               "For.mentors.GAA2"="GAA2Q3",
               "On.our.board.GAA3"="GAA3Q1",
               "Within.our.staff.GAA3"="GAA3Q2",  
               "Within.our.mentors.GAA3"="GAA3Q3"                                                                                                            
             ))

