---
title: "NMRC Survey State Level Completion Report"
author: "Samuel McQuillin"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
classoption: landscape
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r, echo=FALSE}
#Set WD 
setwd("C:/Users/mcquills/R/nmrcsurvey")
#setwd("C:/R/nmrcsurvey")
#Dr. McQuillin's Home Computer
#setwd("C:/Users/Sam/R/nmrcsurvey")

source("mergeclean.R")
statefun("Minnesota")
```
#Completion Report for `r stdfm[1,28]` State

Total number of surveys started: `r dim(stdfm)[1]` 


```{r, echo=FALSE}

 k<-as.data.frame(table(stdfm$STAT))
knitr::kable(k,col.names=c("Status","Number of Surveys"),caption="Table of Surveys completed and Still in Progress")
```

NOTE: Survey respondents who did NOT include a name (personal or organization) or an email are NOT reported in table below.
```{r, echo=FALSE}
stdfmo<-stdfm[order(stdfm$STAT),]
knitr::kable(subset(stdfmo,ORGNAME!="",select=c(ORGNAME,STAT,EMAIL)),caption="List of Organizations and Completion Status",row.names=FALSE,col.names=c("Organization Name","Completion Status", "Email"))
```
